import { Task, AppNotification } from '@/lib/types'

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Ajuste de Copy - Campanha Verão',
    description: 'O cliente pediu para alterar a copy do post 3.',
    status: 'done',
    priority: 'medium',
    assignee: 'Mariana Silva',
    clientName: 'Alpha S/A',
    deadline: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    completedAt: new Date(Date.now() - 86400000).toISOString(),
    history: ['Tarefa criada a partir do WhatsApp', 'Status alterado para done'],
    timeLogs: [
      {
        id: 'l1',
        taskId: 't1',
        startTime: new Date(Date.now() - 86400000 * 2).toISOString(),
        endTime: new Date(Date.now() - 86400000 * 2 + 3600000).toISOString(),
        durationMinutes: 60,
        summary: 'Ajustes de copy',
      },
    ],
  },
  {
    id: 't2',
    title: 'Aprovação Key Visual Anual',
    description: 'Precisamos enviar o KV final para o cliente aprovar.',
    status: 'review',
    priority: 'high',
    assignee: 'Carlos Design',
    clientName: 'Boutique Beta',
    deadline: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    history: ['Design movido para revisão'],
    timeLogs: [],
  },
  {
    id: 't3',
    title: 'Novo Post IG - Lançamento',
    description: 'Criar arte para o lançamento.',
    status: 'in_progress',
    priority: 'high',
    assignee: 'João Social',
    clientName: 'Alpha S/A',
    deadline: new Date(Date.now() + 86400000 * 3).toISOString(),
    createdAt: new Date().toISOString(),
    history: ['Tarefa criada'],
    timeLogs: [],
  },
  {
    id: 't4',
    title: 'Revisão de Textos - Blog',
    description: 'Revisar os 3 artigos para o blog de Abril.',
    status: 'todo',
    priority: 'low',
    assignee: 'Mariana Silva',
    clientName: 'Alpha S/A',
    deadline: new Date(Date.now() + 86400000 * 4).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    history: ['Tarefa criada'],
    timeLogs: [],
  },
]

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    message: 'Nova tarefa atribuída: Aprovação Key Visual Anual',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'n2',
    message: 'Status atualizado: Ajuste de Copy concluído',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
]
